Sender: LSF System <lsfadmin@rivm-lsfsv-l18p.rivm.ssc-campus.nl>
Subject: Job 481586: <python main_TUs_graph_classification.py --dataset PBT_Rep1 --config ./configs/test/TOXGatedGCN1.json> in cluster <RIVM-LSF-PRD> Exited

Job <python main_TUs_graph_classification.py --dataset PBT_Rep1 --config ./configs/test/TOXGatedGCN1.json> was submitted from host <rivm-biohn-l03p.int.ssc-campus.nl> by user <baarsj> in cluster <RIVM-LSF-PRD> at Tue Jun 30 21:12:10 2020
Job was executed on host(s) <rivm-lsfsv-l18p.rivm.ssc-campus.nl>, in queue <bio-tst>, as user <baarsj> in cluster <RIVM-LSF-PRD> at Tue Jun 30 21:11:32 2020
</home/baarsj> was used as the home directory.
</home/baarsj/Documents/GNN_rivm/benchmark> was used as the working directory.
Started at Tue Jun 30 21:11:32 2020
Terminated at Tue Jun 30 21:12:44 2020
Results reported at Tue Jun 30 21:12:44 2020

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python main_TUs_graph_classification.py --dataset PBT_Rep1 --config ./configs/test/TOXGatedGCN1.json
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   8.15 sec.
    Max Memory :                                 103 MB
    Average Memory :                             71.33 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   72 sec.
    Turnaround time :                            34 sec.

The output (if any) follows:

cuda not available
494
preparing 494 graphs for the ALL set...
[!] Dataset:  PBT_Rep1
Time taken: 2.4535s
MODEL DETAILS:

MODEL/Total parameters: GatedGCN 46802
494
preparing 494 graphs for the ALL set...
[!] Dataset:  PBT_Rep1
Time taken: 2.0676s
Traceback (most recent call last):
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'out/TOX_graph_classification/logs/GatedGCN_PBT_Rep1_GPU0_21h12m41s_on_Jun_30_2020/RUN_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_TUs_graph_classification.py", line 468, in <module>
    main()
  File "main_TUs_graph_classification.py", line 458, in main
    train_val_pipeline(MODEL_NAME, DATASET_NAME, params, net_params, dirs)
  File "main_TUs_graph_classification.py", line 126, in train_val_pipeline
    writer = SummaryWriter(log_dir=log_dir)
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/baarsj/.conda/envs/benchmark_gnn/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'out/TOX_graph_classification/logs/GatedGCN_PBT_Rep1_GPU0_21h12m41s_on_Jun_30_2020/RUN_0'
